name: github pages

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: cargo build --release && strip -s target/release/github-action-rss

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/github-action-rss
