name: email notifications

on:
#   push:
#     branches:
#       - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies

      - run: pip install -r requirements.txt

      - run: wget https://github.com/rogeryoungh/github-action-rss/releases/latest/download/github-action-rss && chmod +x ./github-action-rss && ./github-action-rss ./test/feed.opml ./test/

      - run: python3 ./scripts/md2html.py

      - run: python3 ./scripts/send.py
        env:
          MAIL_HOST: '${{ secrets.MAIL_HOST }}'
          MAIL_PASS: '${{ secrets.MAIL_PASS }}'
          MAIL_USER: '${{ secrets.MAIL_USER }}'
          RECEIVERS: '${{ secrets.RECEIVERS }}'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
